[tool.black]
line-length = 88
exclude = '''
/(
  venv
  | migrations
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip = ["venv", "migrations"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
