# Generated by Django 4.2.23 on 2025-07-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(default="English", max_length=50),
        ),
    ]
